import { Container, Header } from "@/components";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Pizzeria-next | Кошик ",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  
}>) {
  return (
        <main className="min-h-screen bg-[#F4F1EE]">
          <Container className="border-gray-200">
          <Header />
          {children}
          </Container>
        </main>
  );
}
